export const PROTOCOL_VERSION = 'war-hearts-v0.1';

export const MessageType = Object.freeze({
  HELLO: 'HELLO',
  READY: 'READY',
  BOARD_COMMIT: 'BOARD_COMMIT',
  BOARD_REVEAL: 'BOARD_REVEAL',
  RPS_CHOICE: 'RPS_CHOICE',
  SHOT: 'SHOT',
  SHOT_RESULT: 'SHOT_RESULT',
  TURN_STATE: 'TURN_STATE',
  CHAT_MESSAGE: 'CHAT_MESSAGE',
  VOICE_STATE: 'VOICE_STATE',
  REMATCH_REQUEST: 'REMATCH_REQUEST',
  REMATCH_ACCEPT: 'REMATCH_ACCEPT',
  REMATCH_REJECT: 'REMATCH_REJECT',
  MATCH_FINISHED: 'MATCH_FINISHED',
  MATCH_ABORTED: 'MATCH_ABORTED',
  MATCH_MODE: 'MATCH_MODE',
  PING: 'PING',
  PONG: 'PONG'
});

export const createMessage = (type, payload = {}) => ({
  v: PROTOCOL_VERSION,
  type,
  payload,
  at: Date.now()
});
